remote_theme: thelehhman/texture
texture:
  title: Ahmet Şimşek
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: thatnotfat
    github:  indatawetrust
    linkedIn: in/ahmetsimsek # format: locale/username
